from __future__ import annotations

from fastapi.responses import HTMLResponse


def index_html() -> HTMLResponse:
    return HTMLResponse(r"""<!doctype html>
<html lang="de">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>INS-EI Core</title>
<style>
:root{font-family:Inter,system-ui,sans-serif;color-scheme:dark;background:#0a0d11;color:#eef2f6;--panel:#12171e;--line:#252c36;--muted:#8995a5;--ok:#78d69c;--warn:#f0c66b;--bad:#ff8080}
*{box-sizing:border-box}body{margin:0;background:#0a0d11}header{height:64px;padding:0 22px;border-bottom:1px solid var(--line);display:flex;align-items:center;justify-content:space-between;position:sticky;top:0;background:#0a0d11ee;backdrop-filter:blur(8px);z-index:3}
.brand b{font-size:18px}.brand span,.muted{color:var(--muted)}button{background:#202731;color:#fff;border:1px solid #36404d;border-radius:9px;padding:8px 12px;cursor:pointer}
.layout{display:grid;grid-template-columns:210px 1fr;min-height:calc(100vh - 64px)}nav{border-right:1px solid var(--line);padding:16px 10px}nav button{display:block;width:100%;text-align:left;margin:3px 0;background:transparent;border-color:transparent;color:#aab4c1}nav button.active{background:#1b222c;color:white;border-color:#2b3542}
main{padding:22px;max-width:1500px}.page{display:none}.page.active{display:block}h1{font-size:25px;margin:0 0 6px}h2{font-size:17px;margin:0 0 12px}.lead{color:var(--muted);margin:0 0 20px}
.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(240px,1fr));gap:14px;margin-bottom:14px}.card{background:var(--panel);border:1px solid var(--line);border-radius:14px;padding:16px;overflow:auto}.label{font-size:12px;color:var(--muted);text-transform:uppercase;letter-spacing:.08em}.big{font-size:25px;font-weight:700;margin:8px 0}.ok{color:var(--ok)}.warn{color:var(--warn)}.bad{color:var(--bad)}
table{width:100%;border-collapse:collapse}td,th{text-align:left;padding:9px;border-bottom:1px solid var(--line);font-size:13px}th{color:var(--muted);font-weight:500}iframe{width:100%;height:650px;border:0;background:white;border-radius:10px}
pre{white-space:pre-wrap;font-size:12px;background:#0d1117;border:1px solid var(--line);padding:12px;border-radius:9px}.pill{display:inline-block;padding:3px 7px;border:1px solid var(--line);border-radius:99px;font-size:11px;margin:2px}
@media(max-width:760px){.layout{grid-template-columns:1fr}nav{display:flex;overflow:auto;border-right:0;border-bottom:1px solid var(--line);padding:8px}nav button{width:auto;white-space:nowrap}main{padding:15px}}
</style>
<script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.7/dist/chart.umd.min.js"></script>
</head>
<body>
<header><div class="brand"><b>INS-EI Core</b> <span>· Client</span></div><div><span id="siteTop" class="muted"></span> <button onclick="location.href='config'">Konfiguration</button> <button onclick="refreshAll()">Aktualisieren</button></div></header>
<div class="layout">
<nav id="nav">
<button class="active" data-page="overview">Übersicht</button>
<button data-page="site">Anlage</button>
<button data-page="plugins">Plugins</button>
<button data-page="signals">Signale</button>
<button data-page="learning">Lernen</button>
<button data-page="forecast">Forecast</button>
<button data-page="optimization">Optimierung</button>
<button data-page="tariffs">Tarife</button>
<button data-page="system">System</button>
</nav>
<main>
<section id="overview" class="page active"><h1>Übersicht</h1><p class="lead">Aktueller Zustand der lokalen INS-EI-Instanz.</p>
<div class="grid"><div class="card"><div class="label">Core</div><div id="health" class="big">…</div><div id="healthDetail"></div></div><div class="card"><div class="label">Safety</div><div id="safety" class="big">…</div><div id="safetyReason"></div></div><div class="card"><div class="label">Learning</div><div id="learningSummary" class="big">…</div><div id="learningDetail"></div></div><div class="card"><div class="label">Autonomie</div><div id="autonomyCount" class="big">…</div><div>Capabilities</div></div></div>
<div class="card"><h2>Komponentenstatus</h2><table><thead><tr><th>Plugin / Instanz</th><th>Status</th><th>Alter</th></tr></thead><tbody id="healthPlugins"></tbody></table></div></section>

<section id="site" class="page"><h1>Anlage</h1><p class="lead">SiteGraph und aktueller Anlagenzustand.</p><div class="card"><iframe src="./site/schema.svg"></iframe></div></section>

<section id="plugins" class="page"><h1>Plugins</h1><p class="lead">Installierte Fähigkeiten und Geräteadapter.</p><div class="card"><table><thead><tr><th>Plugin</th><th>Version</th><th>Capabilities</th></tr></thead><tbody id="pluginRows"></tbody></table></div></section>

<section id="signals" class="page"><h1>Signale</h1><p class="lead">Aktuelle Core-Punkte für Inbetriebnahme und Diagnose.</p><div class="card"><div style="display:flex;gap:8px;flex-wrap:wrap;margin-bottom:12px"><input id="signalFilter" placeholder="Komponente oder Punkt filtern" oninput="renderSignals()" style="min-width:280px;background:#0d1117;color:#fff;border:1px solid #36404d;border-radius:9px;padding:8px"><select id="qualityFilter" onchange="renderSignals()" style="background:#0d1117;color:#fff;border:1px solid #36404d;border-radius:9px;padding:8px"><option value="">Alle Qualitäten</option><option>GOOD</option><option>STALE</option><option>BAD</option></select></div><table><thead><tr><th>Komponente</th><th>Punkt</th><th>Wert</th><th>Einheit</th><th>Qualität</th><th>Alter</th><th>Quelle</th></tr></thead><tbody id="signalRows"></tbody></table></div></section>

<section id="learning" class="page"><h1>Lernen</h1><p class="lead">Was INS-EI über diese Anlage gelernt hat – getrennt nach Modellen.</p><div class="grid"><div class="card"><div class="label">Phase</div><div id="learnPhase" class="big">…</div></div><div class="card"><div class="label">Historie</div><div id="learnHours" class="big">…</div><div id="learnSamples"></div></div></div><div class="card"><table><thead><tr><th>Modell</th><th>Status</th><th>Phase</th><th>Letzter Fit</th><th>Begründung</th></tr></thead><tbody id="modelRows"></tbody></table></div><div class="card" style="margin-top:14px"><h2>Gelernte Ergebnisse</h2><p class="muted">Persistierte Modellwerte aus dem letzten Fit. Reine Beobachtung – keine Steuerfreigabe.</p><div id="learningDetails"></div></div></section>

<section id="forecast" class="page"><h1>Forecast</h1><p class="lead">Gelernter Verbrauch und PV-Ertrag für die nächsten 24 Stunden.</p><div class="grid"><div class="card"><div class="label">Verbrauchsforecast</div><div id="fcLoadTotal" class="big">–</div><div id="fcLoadMeta" class="muted">–</div></div><div class="card"><div class="label">PV-Forecast</div><div id="fcPvTotal" class="big">–</div><div id="fcPvMeta" class="muted">–</div></div></div><div class="card"><h2>Stundenverlauf</h2><div style="height:320px;margin-bottom:18px"><canvas id="forecastChart"></canvas></div><table><thead><tr><th>Zeit</th><th>Verbrauch</th><th>PV</th><th>Netto</th></tr></thead><tbody id="forecastRows"></tbody></table></div><div class="card" style="margin-top:14px"><h2>Forecast-Validierung · letzte 168 h</h2><p class="muted">Nachvollziehbare elektrische Energiebilanz. Power-to-Heat wird als flexible Last aus dem Basisverbrauch entfernt.</p><div class="grid"><div><div class="label">PV</div><div id="valPv" class="big">–</div></div><div><div class="label">Netzbezug / Einspeisung</div><div id="valGrid" class="big">–</div></div><div><div class="label">Batterie Laden / Entladen</div><div id="valBattery" class="big">–</div></div><div><div class="label">Flexible Last · P2H</div><div id="valFlex" class="big">–</div></div><div><div class="label">Gesamtverbrauch rekonstruiert</div><div id="valTotal" class="big">–</div></div><div><div class="label">Unflexibler Basisverbrauch</div><div id="valBase" class="big">–</div></div></div><div id="valHours" class="muted">–</div><div style="margin-top:18px"><h3>Basislast-Diagnose</h3><div id="baseDiagSummary" class="muted">–</div><table><thead><tr><th>Tag</th><th>Validierte Basislast</th></tr></thead><tbody id="baseDiagRows"></tbody></table></div></div></section>

<section id="optimization" class="page"><h1>Optimierung</h1><p class="lead">Autonomie, Entscheidungen und Freigaben. Physische Aktionen bleiben Default-Deny.</p><div class="card"><h2>Capability Autonomy</h2><table><thead><tr><th>Capability</th><th>Modus</th><th>Ausführung</th><th>Grund</th></tr></thead><tbody id="autonomyRows"></tbody></table></div><div class="card" style="margin-top:14px"><h2>Strategy Snapshot</h2><button onclick="evaluateStrategy()">Jetzt auswerten</button><pre id="strategyResult">Noch nicht ausgewertet.</pre></div></section>

<section id="tariffs" class="page"><h1>Tarife</h1><p class="lead">Aktiver Vertrag und Tarif-Simulation.</p><div class="card"><h2>Tarifmodell</h2><p class="muted">Die Core-API für aktive Bezugs-/Einspeisetarife und Szenarien wird als nächster Backend-Baustein angebunden. Die GUI hält dafür bewusst eine eigene Domäne frei.</p><div class="grid"><div><span class="pill">IST: fix / fix</span></div><div><span class="pill">Simulation: dynamisch / fix</span><span class="pill">fix / dynamisch</span><span class="pill">dynamisch / dynamisch</span></div></div></div></section>

<section id="system" class="page"><h1>System</h1><p class="lead">Lokaler Core, Zentrale, Safety und technische Anlagenkonfiguration.</p><div class="grid"><div class="card"><div class="label">Zentrale / MQTT</div><div id="bus" class="big">…</div><div id="busDetail"></div><button onclick="publishBus()">Snapshot senden</button></div><div class="card"><div class="label">Safety</div><div id="systemSafety" class="big">…</div><p id="systemSafetyReason"></p></div></div><div class="card" style="margin-top:14px"><h2>Anlagenkonfiguration</h2><p class="muted">Engineering-Konfiguration als JSON. Änderungen werden vor dem Speichern gegen das SiteConfig-Schema validiert und nach einem Neustart aktiv.</p><input id="configFile" type="file" accept=".json,application/json" onchange="loadConfigFile(this)"><div style="display:flex;gap:8px;margin:12px 0"><button onclick="loadCurrentConfig()">Aktuelle Konfiguration laden</button><button onclick="validateConfig()">Validieren</button><button onclick="saveConfig()">Speichern</button></div><textarea id="configEditor" spellcheck="false" style="width:100%;min-height:420px;box-sizing:border-box;background:#0d1117;color:#eef2f6;border:1px solid #36404d;border-radius:9px;padding:12px;font-family:monospace"></textarea><div id="configResult" class="muted" style="margin-top:10px"></div></div></section>
</main></div>
<script>
function api(path){const b=window.location.pathname.endsWith('/')?window.location.pathname:window.location.pathname+'/';return b+path.replace(/^\//,'')}
async function j(path,opts){const r=await fetch(api(path),opts);const t=await r.text();if(!r.ok)throw new Error('HTTP '+r.status+' '+t.slice(0,120));return t?JSON.parse(t):{}}
function statusClass(v){return ['OK','RUNNING','AUTONOMOUS','READY'].includes(String(v).toUpperCase())?'ok':['FAILED','DEGRADED','ERROR'].includes(String(v).toUpperCase())?'bad':'warn'}
document.querySelectorAll('#nav button').forEach(b=>b.onclick=()=>{document.querySelectorAll('#nav button').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.getElementById(b.dataset.page).classList.add('active')})
let currentSignals=[];
function renderSignals(){const q=(signalFilter?.value||'').toLowerCase(),quality=qualityFilter?.value||'';signalRows.innerHTML=currentSignals.filter(x=>(!q||((x.component_id+' '+x.point).toLowerCase().includes(q)))&&(!quality||String(x.quality).toUpperCase()===quality)).sort((a,b)=>(a.component_id+a.point).localeCompare(b.component_id+b.point)).map(x=>'<tr><td>'+x.component_id+'</td><td>'+x.point+'</td><td>'+String(x.value)+'</td><td>'+(x.unit==null?'–':x.unit)+'</td><td class="'+statusClass(x.quality)+'">'+x.quality+'</td><td>'+Math.round(x.age_seconds||0)+' s</td><td>'+(((x.source||{}).plugin_instance)||'–')+'</td></tr>').join('')}
async function loadCurrentConfig(){try{const x=await j('/system/config');configEditor.value=JSON.stringify(x,null,2);configResult.className='ok';configResult.textContent='Aktuelle Konfiguration geladen.'}catch(e){configResult.className='bad';configResult.textContent=String(e)}}
function loadConfigFile(input){const f=input.files&&input.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{configEditor.value=String(r.result||'');configResult.textContent='Datei geladen – noch nicht gespeichert.'};r.readAsText(f)}
function parsedConfig(){return JSON.parse(configEditor.value)}
async function validateConfig(){try{const x=await j('/system/config/validate',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(parsedConfig())});configResult.className='ok';configResult.textContent='✓ Gültig · '+x.site_id+' · '+x.components+' Komponenten · '+x.relations+' Verbindungen'}catch(e){configResult.className='bad';configResult.textContent='✗ '+String(e)}}
async function saveConfig(){try{const x=await j('/system/config',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(parsedConfig())});configResult.className='ok';configResult.textContent='✓ Gespeichert und validiert. Neustart erforderlich.'}catch(e){configResult.className='bad';configResult.textContent='✗ '+String(e)}}
function renderValidation(v){const t=v.totals||{},k=x=>(Number(x||0)).toFixed(2)+' kWh';valPv.textContent=k(t.pv_kwh);valGrid.textContent=k(t.grid_import_kwh)+' / '+k(t.grid_export_kwh);valBattery.textContent=k(t.battery_charge_kwh)+' / '+k(t.battery_discharge_kwh);valFlex.textContent=k(t.flexible_p2h_kwh);valTotal.textContent=k(t.reconstructed_total_kwh);valBase.textContent=k(t.inflexible_base_kwh);valHours.textContent=(v.hours||0)+' Stunden ausgewertet · flexible Lasten ausgeschlossen: '+((v.flexible_loads_excluded||[]).join(', ')||'–');const d=v.base_load_diagnostics||{};baseDiagSummary.textContent=d.historical_daily_mean_kwh!=null?'Ø vollständige Tage: '+d.historical_daily_mean_kwh.toFixed(2)+' kWh/Tag · aktueller 24h-Forecast: '+Number(d.current_forecast_24h_kwh||0).toFixed(2)+' kWh · Faktor '+Number(d.forecast_vs_history_ratio||0).toFixed(2):'Noch nicht genügend vollständige Tage';baseDiagRows.innerHTML=(d.historical_days||[]).map(x=>'<tr><td>'+x.day+'</td><td>'+Number(x.actual_base_kwh).toFixed(2)+' kWh</td></tr>').join('')}
function forecastQuality(slots){const q=slots.map(x=>((x.metadata||{}).quality||'LEARNING'));return q.includes('FALLBACK')?'LEARNING':(q.every(x=>x==='GOOD')?'GOOD':'MEDIUM')}
let forecastChartInstance=null;
function renderForecast(ts){const s=ts.series||{},load=s['forecast.consumption_energy']||[],pv=s['forecast.pv_energy']||[],imp=s['market.import_price']||[],exp=s['market.export_price']||[];const first24=x=>x.slice(0,24);const l=first24(load),p=first24(pv);const sum=x=>x.reduce((a,b)=>a+Number(b.value||0),0);fcLoadTotal.textContent=l.length?sum(l).toFixed(2)+' kWh / 24 h':'Noch keine Daten';fcPvTotal.textContent=p.length?sum(p).toFixed(2)+' kWh / 24 h':'Noch keine Daten';fcLoadMeta.textContent=l.length?forecastQuality(l)+' · '+((l[0].source)||'–'):'–';fcPvMeta.textContent=p.length?forecastQuality(p)+' · '+((p[0].source)||'–'):'–';if(window.Chart&&document.getElementById('forecastChart')){if(forecastChartInstance)forecastChartInstance.destroy();forecastChartInstance=new Chart(document.getElementById('forecastChart'),{type:'bar',data:{labels:Array.from({length:Math.max(l.length,p.length)},(_,i)=>{const x=l[i]||p[i];return x?new Date(x.start).toLocaleTimeString('de-AT',{hour:'2-digit',minute:'2-digit'}):''}),datasets:[{label:'Verbrauch',data:l.map(x=>Number(x.value||0)),yAxisID:'y'},{label:'PV',data:p.map(x=>Number(x.value||0)),yAxisID:'y'},{type:'line',label:'Bezugspreis',data:imp.slice(0,24).map(x=>Number(x.value||0)),yAxisID:'yPrice',tension:.25},{type:'line',label:'Einspeisepreis',data:exp.slice(0,24).map(x=>Number(x.value||0)),yAxisID:'yPrice',tension:.25}]},options:{responsive:true,maintainAspectRatio:false,interaction:{mode:'index',intersect:false},plugins:{legend:{position:'top'},tooltip:{callbacks:{footer:(items)=>{if(!items.length)return '';const i=items[0].dataIndex;const lv=l[i]?Number(l[i].value):0,pv=p[i]?Number(p[i].value):0;return 'Netto: '+((pv-lv)>=0?'+':'')+(pv-lv).toFixed(3)+' kWh'}}}},scales:{y:{beginAtZero:true,title:{display:true,text:'kWh'}},yPrice:{position:'right',title:{display:true,text:'ct/kWh'},grid:{drawOnChartArea:false}}}}})}const n=Math.max(l.length,p.length);forecastRows.innerHTML=Array.from({length:n},(_,i)=>{const a=l[i],b=p[i],time=(a||b||{}).start||'';const lv=a?Number(a.value):0,pv=b?Number(b.value):0;return '<tr><td>'+String(time).replace('T',' ').slice(0,16)+'</td><td>'+lv.toFixed(3)+' kWh</td><td>'+pv.toFixed(3)+' kWh</td><td>'+((pv-lv)>=0?'+':'')+(pv-lv).toFixed(3)+' kWh</td></tr>'}).join('')}
async function refreshAll(){
 const [h,s,lm,ls,a,p,b,st,ts,fv]=await Promise.allSettled([j('/health'),j('/safety'),j('/learning/models'),j('/learning/status'),j('/autonomy'),j('/plugins'),j('/bus/status'),j('/state'),j('/timeseries'),j('/forecast/validation')]);
 if(h.status==='fulfilled'){const x=h.value;health.textContent=x.status;health.className='big '+statusClass(x.status);healthDetail.textContent=x.site||'';siteTop.textContent=x.site||'';healthPlugins.innerHTML=Object.entries(x.plugins||{}).map(([k,v])=>'<tr><td>'+k+'</td><td class="'+statusClass(v.status)+'">'+v.status+'</td><td>'+(v.last_read_age_seconds==null?'–':Math.round(v.last_read_age_seconds)+' s')+'</td></tr>').join('')}
 if(s.status==='fulfilled'){const x=s.value;const t=x.emergency_stop?'NOT-AUS AKTIV':'Freigegeben';safety.textContent=systemSafety.textContent=t;safety.className=systemSafety.className='big '+(x.emergency_stop?'bad':'ok');safetyReason.textContent=systemSafetyReason.textContent=x.reason||''}
 if(ls.status==='fulfilled'){const x=ls.value;learningSummary.textContent=learnPhase.textContent=x.phase||'–';learnHours.textContent=(x.duration_hours||0).toFixed(1)+' h';learnSamples.textContent=(x.samples||0)+' Samples · '+(x.signals||0)+' Signale';learningDetail.textContent=learnSamples.textContent}
 if(lm.status==='fulfilled'){const models=lm.value.models||[];modelRows.innerHTML=models.map(x=>'<tr><td>'+x.id+'</td><td class="'+statusClass(x.status)+'">'+x.status+'</td><td>'+((x.metadata||{}).phase||'OBSERVATION')+'</td><td>'+((x.metadata||{}).last_fit_at||'–')+'</td><td>'+((x.reason||'–'))+'</td></tr>').join('');learningDetails.innerHTML=models.map(x=>{const m=x.metadata||{};const sections=[['Buffer State V2',m.buffer_state_v2_fit],['Buffer State V1',m.buffer_state_v1_fit],['Thermische Kontexte',m.thermal_context_fit],['Power-to-Heat V2',m.power_to_heat_v2_fit],['Warmwasser',m.dhw_fit],[x.id==='thermal-baseline'?'Temperatur-Baseline':'Legacy-Baseline',m.generic_fit],['Batterie',m.battery_fit],['Elektrik',m.electrical_fit],['PV-Ausrichtungen',m.orientation_fit],['PV-Eingänge',m.input_fit]].filter(y=>y[1]&&Object.keys(y[1]).length);if(!sections.length)return '<div class="card" style="margin:8px 0"><b>'+x.id+'</b><div class="muted">Noch keine auswertbaren Fit-Ergebnisse gespeichert.</div></div>';return '<div class="card" style="margin:8px 0"><b>'+x.id+'</b>'+sections.map(y=>'<h3 style="font-size:14px;margin:14px 0 6px">'+y[0]+'</h3><pre>'+JSON.stringify(y[1],null,2)+'</pre>').join('')+'</div>'}).join('')}
 if(a.status==='fulfilled'){const xs=a.value.capabilities||[];autonomyCount.textContent=xs.length;autonomyRows.innerHTML=xs.map(x=>'<tr><td>'+x.capability+'</td><td class="'+statusClass(x.mode)+'">'+x.mode+'</td><td>'+(x.assessment&&x.assessment.allowed?'EXECUTE':'BLOCK')+'</td><td>'+(x.reason||'–')+'</td></tr>').join('')}
 if(p.status==='fulfilled'){pluginRows.innerHTML=(p.value.plugins||[]).map(x=>'<tr><td>'+x.id+'</td><td>'+(x.version||'–')+'</td><td>'+((x.capabilities||[]).map(c=>'<span class="pill">'+(typeof c==='string'?c:(c.id||c.name||JSON.stringify(c)))+'</span>').join('')||'–')+'</td></tr>').join('')}
 if(b.status==='fulfilled'){const x=b.value;bus.textContent=x.enabled?(x.connected?'VERBUNDEN':'GETRENNT'):'DEAKTIVIERT';bus.className='big '+(x.connected?'ok':x.enabled?'bad':'warn');busDetail.textContent=(x.host||'–')+':'+(x.port||'–')}
 if(st.status==='fulfilled'){currentSignals=st.value.points||[];renderSignals()}
 if(ts.status==='fulfilled')renderForecast(ts.value)
 if(fv.status==='fulfilled')renderValidation(fv.value)
}
async function evaluateStrategy(){strategyResult.textContent='Auswertung…';try{strategyResult.textContent=JSON.stringify(await j('/strategy/evaluate',{method:'POST'}),null,2)}catch(e){strategyResult.textContent=String(e)}}
async function publishBus(){try{await j('/bus/publish',{method:'POST'});refreshAll()}catch(e){alert(e)}}
refreshAll();setInterval(refreshAll,10000)
</script></body></html>""")
